name: Run openCart Batch Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-reclamation-batch-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run batch script
      run: .\run.bat